name: 'Commit tagger'
description: 'Tag commit with a given version'
author: 'Thiago Vaz Dias'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  tag:
    description: 'Tag text'
    default: '0.1.0'
  commit-sha:
    description: optional commit sha to apply the tag to
  move-existing:
    description: 'true to recreate the tag if it already exists'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
